### ISSUE TITLE
pre-training weight

### ISSUE THREAD

**Issue by zhanglaoban-kk** [SLDGroup/MobileViG#2]
Can you tell me how to load the pre-training weights to the model after downloading them as a .pth file?

**Comment by mmunir127** [comment]
Hello,

Please refer to the README testing image classification section for loading pretrained weights for image classification. Please refer to the README testing object detection & instance segmentation section for loading pretrained weights for object detection & instance segmentation.

Thank you!

**Comment by zhanglaoban-kk** [comment]
Hello，Thanks for getting back to me.
My doubt is that the model is used as a model for image classification, but the pre-training weights for image classification on mageNet-1K are .tar file extension, does this need to be unzipped and then load the pre-training weights, but after unzipping it is not a .pth file, it is three files, how can this be loaded into the model. It's not like detection's pre-training weights are .pth files.
Thank you!

**Comment by zhanglaoban-kk** [comment]
Hello，Thanks for getting back to me. 
My doubt is that the model is used as a model for image classification, but the pre-training weights for image classification on mageNet-1K are .tar file extension, does this need to be unzipped and then load the pre-training weights, but after unzipping it is not a .pth file, it is three files, how can this be loaded into the model. It's not like detection's pre-training weights are .pth files. 
Thank you!

**Comment by mmunir127** [comment]
Hello,

This does not need to be uncompressed to load the pre-training weights. You can load the weights directly in the .pth.tar format using the image classification code provided.

**Comment by zhanglaoban-kk** [comment]
Ok, I tried not to unzip two days ago, the loading was successful, thank you very much for your reply and help.

**Comment by mmunir127** [comment]
No problem! Thank you very much for your questions!
